CREATE TABLE MYFILE (
    IDX NUMBER PRIMARY KEY
    , NAME VARCHAR2(50) NOT NULL
    , TITLE VARCHAR2(200) NOT NULL
    , CATE VARCHAR2(30)
    , OFILE VARCHAR2(100) NOT NULL
    , SFILE VARCHAR2(30) NOT NULL
    , POSTDATE DATE DEFAULT SYSDATE NOT NULL
);

COMMENT ON COLUMN MYFILE.IDX IS '일련번호';
COMMENT ON COLUMN MYFILE.NAME IS '작성자';
COMMENT ON COLUMN MYFILE.TITLE IS '제목';
COMMENT ON COLUMN MYFILE.CATE IS '카테고리';
COMMENT ON COLUMN MYFILE.OFILE IS '원본 파일명';
COMMENT ON COLUMN MYFILE.SFILE IS '저장된 파일명';
COMMENT ON COLUMN MYFILE.POSTDATE IS '등록한 날짜';

CREATE SEQUENCE SEQ_MYFILE_IDX INCREMENT BY 1
                                START WITH 0
                                MINVALUE 0
                                NOMAXVALUE
                                NOCYCLE
                                NOCACHE;
                                
INSERT INTO MYFILE VALUES (SEQ_MYFILE_IDX.NEXTVAL, '작성자', '제목'||SEQ_MYFILE_IDX.NEXTVAL||'입니다', '카테고리', '원본 파일명', '저장된 파일명', SYSDATE);