CREATE TABLE MVCBOARD (
    IDX NUMBER PRIMARY KEY
    , NAME VARCHAR2(50) NOT NULL
    , TITLE VARCHAR2(200) NOT NULL
    , CONTENT VARCHAR2(2000) NOT NULL
    , POSTDATE DATE DEFAULT SYSDATE NOT NULL
    , OFILE VARCHAR2(200)
    , SFILE VARCHAR2(30)
    , DOWNCOUNT NUMBER DEFAULT 0 NOT NULL
    , PASS VARCHAR2(50) NOT NULL
    , VISITCOUNT NUMBER DEFAULT 0 NOT NULL 
);

COMMENT ON COLUMN MVCBOARD.IDX IS '일련번호';
COMMENT ON COLUMN MVCBOARD.NAME IS '작성자 이름';
COMMENT ON COLUMN MVCBOARD.TITLE IS '제목';
COMMENT ON COLUMN MVCBOARD.CONTENT IS '내용';
COMMENT ON COLUMN MVCBOARD.POSTDATE IS '작성일';
COMMENT ON COLUMN MVCBOARD.OFILE IS '원본 파일명';
COMMENT ON COLUMN MVCBOARD.SFILE IS '저장된 파일명';
COMMENT ON COLUMN MVCBOARD.DOWNCOUNT IS '다운로드 횟수';
COMMENT ON COLUMN MVCBOARD.PASS IS '비밀번호';
COMMENT ON COLUMN MVCBOARD.VISITCOUNT IS '조회수';

CREATE SEQUENCE SEQ_MVCBOARD_NUM INCREMENT BY 1
                                START WITH 1
                                MINVALUE 1
                                NOMAXVALUE
                                NOCYCLE
                                NOCACHE;

INSERT INTO MVCBOARD VALUES (SEQ_MVCBOARD_NUM.NEXTVAL, 'test', '제목입니다', '내용입니다', SYSDATE, '', '', 0, '1234', 0);